config/routes.rb
CourseMatch::Application.routes.draw do
  resources :users
  resources :sessions, only:[:new, :create, :destroy]
  resources :courses
  resources :enrollments, only:[:new,:create,:destroy]
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via:'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/admin', to: 'static_pages#admin', via:'get'
  match '/logout', to: 'sessions#destroy', via:'delete'

  

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :enrollments, dependent: :destroy
  	has_many :users, through: :enrollments

	validates :crn, presence:true
	validates :course_number, presence:true
	validates :course_name, presence:true
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :enrollments, dependent: :destroy
  has_many :courses, through: :enrollments

  # always make sure it is downcase before a save
  before_save {self.email = self.email.downcase}
  before_save {self.first_name = self.first_name.downcase}
  before_save {self.last_name = self.last_name.downcase}
  before_create :create_remember_token
  validates :first_name, presence: true, length: {maximum:20}
  validates :last_name, presence: true, length: {maximum:20}
  # regex makes sure it is northeastern email address
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@husky.neu.edu\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}, length: {maximum:30}
  validates :password, length: {minimum:6}
  has_secure_password

  # enroll this user in given course

  def enroll!(course_id)
    self.enrollments.create!(course_id:course_id)
  end

  def drop!(course_id)
    self.enrollments.find_by(course_id:course_id).destroy!
  end

  # generate ea new random remember_token
  def User.new_remember_token
  	return SecureRandom.urlsafe_base64
  end
  # encrypt a remember_me token
  def User.encrypt(token)
  	return Digest::SHA1.hexdigest(token.to_s)
  end


  private
  	# create remember me token for this user
  	def create_remember_token
  		self.remember_token = User.encrypt(User.new_remember_token)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :admin_user, only:[:new]

	def show
		@course = Course.find(params[:id])
	end

	def index
		@courses = Course.all
	end
	def new
		@course = Course.new
	end
	def create
		course = Course.new(course_params)
		if course.save
			flash[:success] = "Course Created"
			redirect_to course
		else
			flash[:danger] = "Creation Failed" 
			redirect_to '/admin'
		end
	end



	private

		def course_params
			return params.require(:course).permit(:crn,:course_name,:course_number,:time)
		end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
	before_action :signed_in_user
	def create
		current_user.enroll!(params[:enrollment][:course_id])
		redirect_to root_url
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:danger] = "Invalid username/password combination"
      render 'new' 
    end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
    	redirect_to current_user
    end
  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only:[:edit, :update, :show, :index,:delete]
  before_action :correct_user, only:[:edit, :update]
  before_action :admin_user, only:[:destroy]

  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
  def create
    @user = User.new(user_params())
    if @user.save
      sign_in(@user)
      flash[:success] = "Your account has been created"
      redirect_to @user
    else 
      render 'new'
    end
  end
  def destroy
    User.find(params[:id]).destroy
    redirect_to root_url
  end

  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

    def user_params
      return params.require(:user).permit(:first_name,:last_name,:email,:password,:password_confirmation)
    end

      ### Before Filters




end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title)
    base = "Course Watch"
    if title.empty?
      return base
    else
      return "#{base} | #{title}"
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def sign_out
		current_user.update_attribute(:remember_token,User.encrypt(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end
	def signed_in?
		return !current_user.nil?
		
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)	
	end

	def current_user?(user)
		return current_user == user
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def admin_user
    	unless current_user.admin?
      		redirect_to(root_url)
   		end
	end

	def admin?()
		return current_user.admin
	end

	  def signed_in_user
    unless signed_in?
      store_location
      flash[:warning] = "You need to sign in to access that page"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      redirect_to(root_url)
    end
    
  end

    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def admin

	end
  
end

app/helpers/users_helper.rb
module UsersHelper
  # returns gravatar image for user email
  def gravatar_for(user,size=80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    return link_to image_tag(gravatar_url, alt: user.first_name, class: "gravatar", width:size,height:size),user
  end

  
end

app/views/courses/index.html.erb
<ul>
<% @courses.each do |course| %>
	<li><%= link_to("#{course.course_number} #{course.course_name}",course) %></li>
<% end %>
</ul>

app/views/courses/new.html.erb
<% provide(:title,"New Course") %>
<div class="container">
<h1 class="center"> New Course </h2>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@course) do |f| %>

        <%= f.text_field :crn, placeholder:"CRN" %>

        <%= f.text_field :course_name, placeholder:"Course Name" %>

        <%= f.text_field :course_number, placeholder:"Course Number" %>

        <%= f.text_field :time, placeholder:"Time" %>

        <%= f.submit "Create class", class: "btn btn-large btn-primary btn-signup" %>
      <% end %>

    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="container">
<h1><%= @course.course_name %> - (<%= @course.crn %>)</h1>
<%= form_for (current_user.enrollments.new()) do |f|  %>
	<%= f.hidden_field :course_id,value:@course.id %>
	<%= f.submit "Add Class", class: "btn btn-large btn-primary btn-signup" %>
<% end %>
<h4><%= @course.course_number %></h4>
<div class="container users">
		<ul>
			<%= render partial: 'shared/user', collection:@course.users %>
		</ul>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<header>
<%= render 'shared/navigation' %>
<div class="container">
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%=value %></div>
  <% end %>
</div>
</header>
<body>

<%= yield %>
<%= render 'shared/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count,"error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Course Watch</a>
    by John Kohler
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href=<%= root_path %>>Course Watch</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if signed_in?  %>
      <% if admin? %>
        <li><%= link_to("Admin",'/admin') %></li>
      <% end %>
      <li><%= link_to("Profile",current_user) %></li>
      <li><%= link_to("Courses",courses_path)%></li>
      <li><%= link_to("Edit",edit_user_path(current_user)) %></li>
      <li><%= link_to("Logout",logout_path, method:"delete") %></li>
      <% else %>
      <li><a href=<%= root_path %>>Home</a></li>
      <li><%= link_to "Login", login_path %></li>
      <% end %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Help</a></li>
          <li><a href="#">FAQ</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/shared/_sidebar.html.erb
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= gravatar_for(@user) %>
        <%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}" %>
      </h1>

    </section>

  </aside>



</div>

app/views/shared/_user.html.erb
<li>

		<%= gravatar_for(user) %> <%= link_to("#{user.first_name.capitalize} #{user.last_name.capitalize}",user) %>
		<% if current_user.admin? && !current_user?(user) %>
			| <%= link_to("delete",user,method: :delete) %>
		<% end %>
</li>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<h1> About </h1>

app/views/static_pages/admin.html.erb
<div class="container">
<%= link_to("New Course",new_course_path) %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron">
  <div class="container">
    <h1 class="white">Course Watch</h1>
    <h2>See What Classes Your Friends Are Taking</h2>
    <%= link_to 'Sign Up Now!',signup_path,class: "btn btn-large btn-primary" %>
</div>

</div>

app/views/users/edit.html.erb
<%= provide(:title,"Edit Profile") %>
<h1 class="center"> Update Profile</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			 <%= render 'shared/error_messages' %>

			<%= f.label :first_name %>
			<%= f.text_field :first_name %>

			<%= f.label :last_name %>
			<%= f.text_field :last_name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Update Info", class: "btn btn-large btn-primary btn-signup" %>

		<% end %>
			<%= gravatar_for(@user) %>
			<a href="http://gravatar.com/emails">Change</a>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<h1 class="text-center"> All Users</h1>
	<div class="container users">
		<ul>
			<%= render partial: 'shared/user', collection:@users %>
		</ul>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title,"Signup") %>
<div class="container">
<h1 class="center"> Sign up </h2>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name, autofocus:"1" %>

        <%= f.label :last_name %>
        <%= f.text_field :last_name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary btn-signup" %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,"#{@user.first_name} #{@user.last_name}") %>
<div class="container">
  <%= render 'shared/sidebar' %>
  <ul>
  <% @user.courses.each do |course| %>
  <li><%= link_to course.course_name,course %></li>
  <% end %>
</ul>
</div>